### ISSUE TITLE
Error in in build with esp idf 4.4 "tinyusb.h: No such file or directory #include "tinyusb.h""

### ISSUE THREAD

**Issue by gt-inno** [nopnop2002/esp-idf-can2usb#2]
After menuconfig and set target the build fails with the error "tinyusb.h: No such file or directory #include "tinyusb.h"

**Comment by nopnop2002** [comment]
What version of ESP-IDF are you using?

```
idf.py --version
```

**Comment by nopnop2002** [comment]
I built with this.
It builds correctly.

```
$ idf.py --version
ESP-IDF v4.4.3-347-g9ee3c8337d

Project build complete. To flash, run this command:
/home/nop/.espressif/python_env/idf4.4_py3.9_env/bin/python ../../esp-idf/components/esptool_py/esptool/esptool.py -p (PORT) -b 460800 --before default_reset --after hard_reset --chip esp32s2  write_flash --flash_mode dio --flash_size detect --flash_freq 80m 0x1000 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0x10000 build/can2usb.bin 0x110000 build/storage.bin
or run 'idf.py -p (PORT) flash'
```

An error may occur with 4.4.1 or 4.4.2.

**Comment by gt-inno** [comment]
ESP-IDF v4.4.3-dirty

**Comment by nopnop2002** [comment]
Since dirty is old, I think it will work if you update it.

Try this.
https://github.com/espressif/esp-idf/tree/release/v4.4
And build esp-idf/examples/peripherals/usb/tusb_console


---

The latest stable version is 5.0.

**Comment by nopnop2002** [comment]
USB can only use ESP32S2 and ESP32S3.
ESP32 cannot use USB.
**ESP32 gives the following error:**

```
/home/nop/esp-idf/examples/peripherals/usb/tusb_serial_device/main/tusb_serial_device_main.c:18:10: fatal error: tinyusb.h: No such file or directory
 #include "tinyusb.h"
```

# Hardware requirements
1. ESP32-S2/S3 Development board   
Because the ESP32-S2/S3 does support USB OTG.
